#!/usr/bin/env bash

# choose the year you want to create in your account
YEAR="1989" #ex
# enter your username
USERNAME="github_user" #ex
# enter your access token
ACCESS_TOKEN="my_super_secret_token" #ex

[ -z "$USERNAME" ] && exit 1
[ -z "$ACCESS_TOKEN" ] && exit 1
[ ! -d "$YEAR" ] && mkdir "$YEAR"

cd "$YEAR" || exit
git init
echo "**${YEAR}** - Generated by LordLucass" >README.MD
git add .
git commit -m "${YEAR} Initial commit"
git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${YEAR}.git"
git branch -M main

for MONTH in $(seq -w 01 12); do
  LAST_DAY=$(cal $MONTH $YEAR | awk 'NF {DAYS = $NF}; END {print DAYS}')
  for DAY in $(seq -w 01 $LAST_DAY); do
    # random hour between 00 and 23
    HOUR=$(shuf -i 0-23 -n 1)

    # random minute between 00 and 59
    MINUTE=$(shuf -i 0-59 -n 1)

    # random second between 00 and 59
    SECOND=$(shuf -i 0-59 -n 1)

    # create commit with empty file
    echo >"$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND".txt
    GIT_AUTHOR_DATE="$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND" \
      GIT_COMMITTER_DATE="$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND" \
      git add .
    GIT_AUTHOR_DATE="$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND" \
      GIT_COMMITTER_DATE="$YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND" \
      git commit -m "Empty commit on $YEAR-$MONTH-$DAY $HOUR:$MINUTE:$SECOND"
  done
done

git push -u origin main -f
cd ..
rm -rf "$YEAR"
